version: '2'
services:
    inventorymanagementsystem-app:
        image: inventorymanagementsystem
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://inventorymanagementsystem-postgresql:5432/InventoryManagementSystem
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=inventorymanagementsystem-elasticsearch:9300
        ports:
            - 8080:8080
    inventorymanagementsystem-postgresql:
        extends:
            file: postgresql.yml
            service: inventorymanagementsystem-postgresql
    inventorymanagementsystem-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: inventorymanagementsystem-elasticsearch
