version: '2'
services:
    inventorymanagementsystem-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/InventoryManagementSystem/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=InventoryManagementSystem
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
